version: '3'
services:
  redis:
    restart: always
    image: "redis:latest"
    container_name: incubator-redis
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"

